Move llvmlite to LLVM 20
numba/llvmlite pull request #1092
Opened 2024-10-25 10:09 UTC by yashssh

~Depends and contains changes introduced with #1091~ 

List of changes in this MR
- Delete legacy pass manager code
- Delete typed pointer code
- Update APIs that needs updating for llvm19
  - Pass registry and initialization APIs support dropped: https://reviews.llvm.org/D145043
  - `StandardIntrumentations` checks function analysis invalidation in module passes as well: https://reviews.llvm.org/D146160
  - `TargetParser.getHostCPUFeatures()` returns a `StringMap`: https://github.com/llvm/llvm-project/pull/97824
  - `CodeGenOpt::Level` turned into an enum class: https://github.com/llvm/llvm-project/pull/66295
- Update refprune pass and its tests 

TODO: 
- run with remarks feature ~and pass timer features~ have to be added 

(edited by @gmarkall to link to relevant review for dropping initialization APIs)

2024-11-05 14:18 UTC, gmarkall commented
/azp run

2025-01-13 08:31 UTC, rj-jesus commented on ffi/core.cpp
> +    // Opaque pointer support dropped https://reviews.llvm.org/D139441
I believe you meant "**Typed** pointer support dropped"?

2025-01-13 08:32 UTC, rj-jesus commented on ffi/core.cpp
> +    // Opaque pointer support dropped https://reviews.llvm.org/D139441
(Same as above.)

2025-01-15 06:33 UTC, yashssh commented on ffi/core.cpp
> +    // Opaque pointer support dropped https://reviews.llvm.org/D139441
You are right, thanks for spotting! Will update :)

2025-03-03 02:21 UTC, detrout commented
Hi,

I found time to try and work on getting llvmlite to build with a version of llvm that's in Debian.

I took this pull request and rebased it against 0.44.0, and then collapse the branch into a single diff to apply to the a Debian 0.44.0 version of the llvmlite package.

I pushed what I've manage to get done to https://github.com/detrout/llvmlite/tree/llvm19

I noticed there's a bunch of code removed this pull request in a migration from passmanager to newpassmanager, though the llvmlite HEAD branch currently has both passmanager and newpassmanager modules. I don't know if it's intended to remove passmanager or not?

The merged code almost works (at least on Debian unstable on a x86 cpu with python 3.13.2 and llvm-19.1.7) it's down to two test failures.

```
======================================================================             
FAIL: test_object_file (llvmlite.tests.test_binding.TestObjectFile.test_object_file)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.13_llvmlite/build/llvmlite/tests/test_binding.py", line 2443, in test_object_file
    self.assertTrue(s.size() > 0)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
AssertionError: False is not true
                               
======================================================================
FAIL: test_lookup_current_process_symbol_fails (llvmlite.tests.test_binding.TestOrcLLJIT.test_lookup_current_process_symbol_fai
ls)                  
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.13_llvmlite/build/llvmlite/tests/test_binding.py", line 1493, in test_lookup_curre
nt_process_symbol_fails                                        
    with self.assertRaisesRegex(RuntimeError, msg):
         ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
AssertionError: RuntimeError not raised
                                                                                                                               
----------------------------------------------------------------------
Ran 379 tests in 7.699s

FAILED (failures=2, skipped=2)
```

I did try running the build under arm64 using qemu and funny story, all the tests passed.

```
Ran 379 tests in 171.947s
                               
OK (skipped=19) 
```

2025-03-03 18:00 UTC, detrout commented
I'd also managed to run the two test failures in pdb, and for the llvmlite.tests.test_binding.TestObjectFile.test_object_file

I found a possibly useful thing that there was a .text segment that had no contents. Though there were other text segments like (I think) .ltext that had some contents

2025-03-19 05:35 UTC, detrout commented
I am deep into places I don't understand and could use help. This is the test failure from test_binding.py::TestObjectFile.test_object_file() on an older x86_64 cpu

I figured out how to print the assembly code.

This is with llvm-19 and there's a .section section that the llvm-15 version doesn't use
```
        .text
        .file   "asm_sum.c"
        .section        .ltext,"axl",@progbits
        .globl  sum
        .p2align        4, 0x90
        .type   sum,@function
sum:
        .cfi_startproc
        leal    (%rdi,%rsi), %eax
        retq
.Lfunc_end0:
        .size   sum, .Lfunc_end0-sum
        .cfi_endproc

        .type   glob,@object
        .section        .lbss,"awl",@nobits
        .globl  glob
        .p2align        2, 0x0
glob:
        .long   0
        .size   glob, 4

        .type   glob_b,@object
        .globl  glob_b
glob_b:
        .byte   0
        .size   glob_b, 1

        .type   glob_f,@object
        .section        .ldata,"awl",@progbits
        .globl  glob_f
        .p2align        2, 0x0
glob_f:
        .long   0x3fc00000
        .size   glob_f, 4

        .type   glob_struct,@object
        .section        .lbss,"awl",@nobits
        .globl  glob_struct
        .p2align        4, 0x0
glob_struct:
        .zero   24
        .size   glob_struct, 24

        .section        ".note.GNU-stack","",@progbits
```

This is what was generated from llvm 15.0.7 from conda.

```
        .text                                                                                                            
        .file   "asm_sum.c"                                                                                              
        .globl  sum                                                                                                      
        .p2align        4, 0x90                                                                                          
        .type   sum,@function                                                                                            
sum:                                                                                                                     
        .cfi_startproc                                                                                                   
        leal    (%rdi,%rsi), %eax                                                                                        
        retq                                                                                                             
.Lfunc_end0:                                                                                                             
        .size   sum, .Lfunc_end0-sum                                                                                     
        .cfi_endproc                                                                                                     
                                                                                                                         
        .type   glob,@object                                                                                             
        .bss                                                                                                             
        .globl  glob                                                                                                     
        .p2align        2                                                                                                
glob:                                                                                                                    
        .long   0
        .size   glob, 4

        .type   glob_b,@object
        .globl  glob_b
glob_b:
        .byte   0
        .size   glob_b, 1

        .type   glob_f,@object
        .data
        .globl  glob_f
        .p2align        2
glob_f:
        .long   0x3fc00000
        .size   glob_f, 4

        .type   glob_struct,@object
        .bss
        .globl  glob_struct
        .p2align        4
glob_struct:
        .zero   24
        .size   glob_struct, 24

        .section        ".note.GNU-stack","",@progbits
```

2025-03-19 05:43 UTC, yashssh commented
Hi @detrout, thanks for looking into this! The pull request is due a rebase/merge of main for a long time now. The time I created this pull request all tests were passing which obviously isn't the case right now. May I know what are you trying to do with these changes? Meanwhile let me try running the tests again locally.

2025-03-19 06:21 UTC, detrout commented
What's going on is Debian is coming close to a freeze and our release team dropped our llvm-15 for having too many unfixed bugs. which then removed llvmlite, and that removes numba, and that breaks a whole bunch of scientific python packages. We do have llvm-19 and I when I saw this pull request and thought I'd take a stab at merging it.

What I did was to take the original pull request and rebase it against the 0.44.0 release of llvmlite, to try and get something that might be reasonable for Debian to ship. So that's why I was aiming for the release version of llvmlite instead of HEAD.

At this point I made progress more out of stubbornness than any deep understanding of llvm. Though I'm learning bits as I try to figure out whats going on.

I pushed my updated debian package to https://salsa.debian.org/diane/llvmlite

Though unlike the github version that has a flattened version of the llvm-19 compatibility patch.

2025-03-19 06:49 UTC, yashssh commented
> What's going on is Debian is coming close to a freeze and our release team dropped our llvm-15 for having too many unfixed bugs. which then removed llvmlite, and that removes numba, and that breaks a whole bunch of scientific python packages.

I'm not sure if this helps but llvmlite v0.44 do support LLVM 16 out of the box https://llvmlite.readthedocs.io/en/latest/release-notes.html

2025-03-19 08:26 UTC, picca commented
It seems that the minimum version available in Debian testing is llvm-18

2025-03-20 03:17 UTC, detrout commented
I added 2 commits to deal with the test failures with llvm-19 at https://github.com/detrout/llvmlite/commits/llvm19/

what would you like next? try to rebase that change set against HEAD?

2025-03-20 03:23 UTC, yashssh commented
> what would you like next? try to rebase that change set against HEAD?

For this PR? I don't think a rebase is required, I did merge the main branch into it. We would have to wait for the reviews to move forward. Right now https://github.com/numba/numba/pull/9676 is the first hurdle before this can be merged.

2025-03-20 08:48 UTC, rj-jesus commented on ffi/core.cpp
> +    // Opaque pointer support dropped https://reviews.llvm.org/D139441
I think we can remove these comments (and the same below).

2025-03-20 12:34 UTC, gmarkall commented
@yashssh Will numba/numba#9676 also be needed in Numba for it to work with LLVM >= 17? Would @detrout need to grab that and incorporate it into the Debian sources?

2025-03-21 16:24 UTC, detrout commented
My first stab at building debianianized  numba 0.61.0 with this patched version of llvmlite 0.44 didn't work and I need to figure out why.

Thank you all for highlighting more pull requests that might be needed, hopefully I'll have some time soon to try and start plugging them together.

2025-03-26 08:50 UTC, yashssh commented
@detrout we have rebased the required llvmlite LLVM19 changes on top of last release (v0.44) #1182 combined with necessary numba changes numba/numba#10011 should allow you to build and test everything with LLVM19. You might still have to add workarounds for the x86 failures you saw.

2025-04-09 04:48 UTC, detrout commented
llvmlite build on x86_64 and on arm64 (under qemu) with the recommend numba patch https://github.com/numba/numba/pull/10011 and https://github.com/numba/numba/commit/1e2fb1d1c81880a645345991eb48e39b578e119d.patch

I was able to get numba to build using llvmlite 0.44 with llvm-19. it built and ran it's tests under x86_64 but I got a timeout error for arm64 under qemu.... Though I know that numba tests take forever.

2025-05-29 10:55 UTC, gmarkall commented on ffi/memorymanager.h
> -#endif
(I don't think this is a critical issue for this PR though... Happy for it to be left as-is... one day I'd like to imagine we're moved over to OrcJIT and JITLink so that this code is no longer needed)

2025-05-29 11:12 UTC, gmarkall commented on llvmlite/binding/targets.py
> +_object_formats = {
Historically this got out of sync with `Triple.h` in LLVM., I've just checked - this still matches the `ObjectFormatType` enum in `Triple.h` in LLVM 19.

2025-05-30 10:54 UTC, gmarkall commented on ffi/build.py
> +            pass
This `if .. pass` pattern feels a bit funny. I think we can get rid of it with a change below:
```suggestion
```

2025-05-30 10:55 UTC, gmarkall commented on ffi/build.py
> +        elif version > 20:
This feels a bit funny. I think we can change it to:

```suggestion
        if version > 20:
```

with a corresponding change below:

2025-05-30 10:55 UTC, gmarkall commented on ffi/build.py
> +        else:
Corresponding change to the above:
```suggestion
        elif version < 20:
```

2025-05-30 11:37 UTC, gmarkall commented
With this PR and the package built by #1226, I get:

```
$ gdb --args python runtests.py 

(gdb) run

Starting program: /home/gmarkall/miniforge3/envs/test-llvmlite-20-py311/bin/python runtests.py
..s..
Program received signal SIGSEGV, Segmentation fault.
0x00007fffefe6635a in llvm::RegisterTargetMachine<llvm::X86TargetMachine>::Allocator(llvm::Target const&, llvm::Triple const&, llvm::StringRef, llvm::StringRef, llvm::TargetOptions const&, std::optional<llvm::Reloc::Model>, std::optional<llvm::CodeModel::Model>, llvm::CodeGenOptLevel, bool) () from /home/gmarkall/numbadev/llvmlite/llvmlite/binding/libllvmlite.so
(gdb) bt
#0  0x00007fffefe6635a in llvm::RegisterTargetMachine<llvm::X86TargetMachine>::Allocator(llvm::Target const&, llvm::Triple const&, llvm::StringRef, llvm::StringRef, llvm::TargetOptions const&, std::optional<llvm::Reloc::Model>, std::optional<llvm::CodeModel::Model>, llvm::CodeGenOptLevel, bool) () from /home/gmarkall/numbadev/llvmlite/llvmlite/binding/libllvmlite.so
#1  0x00007fffefd77dd6 in llvm::Target::createTargetMachine (this=0x7ffff6a87d20 <llvm::getTheX86_64Target()::TheX86_64Target>, 
    TT=..., CPU=..., Features=..., Options=..., RM=..., CM=..., OL=llvm::CodeGenOptLevel::Default, JIT=true)
    at /home/gmarkall/miniforge3/envs/test-llvmlite-20-py311/include/llvm/MC/TargetRegistry.h:462
#2  0x00007fffefd78a6c in LLVMPY_CreateTargetMachine (T=0x7ffff6a87d20 <llvm::getTheX86_64Target()::TheX86_64Target>, 
    Triple=0x7ffff748af50 "x86_64-unknown-linux-gnu", CPU=0x555555aaa368 <_PyRuntime+9096> "", 
    Features=0x555555aaa368 <_PyRuntime+9096> "", OptLevel=2, RelocModel=0x7fffef57cf20 "default", 
    CodeModel=0x7fffef57ccb0 "jitdefault", PrintMC=0, JIT=1, ABIName=0x555555aaa368 <_PyRuntime+9096> "")
```

@yashssh Have you run on x86 as well? I presume you have not encountered segfaults in the test suite so far?

2025-08-18 14:23 UTC, esc commented
@yashssh question: we are going to be merging https://github.com/numba/llvmlite/pull/1252 very soon -- would you be able to rebase this PR onto `main` at short notice this week? I'm trying to push the next llvmlite release forward and would like to include this change.

2025-08-18 16:28 UTC, yashssh commented
Thanks @esc! Yeah I can get to it

2025-08-18 16:35 UTC, emilazy commented
(Not to add notification noise, but as a distro maintainer that has to deal with way too many unmaintained LLVM versions, thank you very much for working on this and I look forward to the release!)

2025-08-18 17:36 UTC, esc commented
> Thanks @esc! Yeah I can get to it

OK, great, I'll keep you posted!

2025-08-19 19:53 UTC, esc commented
@yashssh the PR @ https://github.com/numba/llvmlite/pull/1252 is now merged, I think you can merge `main` into this now and resolve the conflicts.

2025-08-20 10:00 UTC, esc commented
I saw these merge conflicts:


```
Unmerged paths:
	both modified:   ffi/CMakeLists.txt
	deleted by us:   ffi/Makefile.freebsd
	deleted by us:   ffi/Makefile.linux
	deleted by us:   ffi/Makefile.osx
	both modified:   ffi/build.py
	both modified:   ffi/custom_passes.cpp
	both modified:   ffi/newpassmanagers.cpp
```

Three removes, two clobbers and some cpp resolution?

2025-08-20 10:06 UTC, esc commented
The RTD jobs fail because of:

```

-- Found LLVM 15.0.7
--
  | -- Using LLVMConfig.cmake in: /home/docs/checkouts/readthedocs.org/user_builds/llvmlite/conda/1092/lib/cmake/llvm
  | CMake Error at CMakeLists.txt:41 (message):
  | LLVM CMake export states LLVM version is 15, llvmlite only officially
  | supports 20.


```

2025-08-20 10:08 UTC, yashssh commented
> The RTD jobs fail because of:
> 
> ```
> 
> -- Found LLVM 15.0.7
> --
>   | -- Using LLVMConfig.cmake in: /home/docs/checkouts/readthedocs.org/user_builds/llvmlite/conda/1092/lib/cmake/llvm
>   | CMake Error at CMakeLists.txt:41 (message):
>   | LLVM CMake export states LLVM version is 15, llvmlite only officially
>   | supports 20.
> ```

This is expected right?

2025-08-20 10:13 UTC, esc commented
> > The RTD jobs fail because of:
> > ```
> > 
> > -- Found LLVM 15.0.7
> > --
> >   | -- Using LLVMConfig.cmake in: /home/docs/checkouts/readthedocs.org/user_builds/llvmlite/conda/1092/lib/cmake/llvm
> >   | CMake Error at CMakeLists.txt:41 (message):
> >   | LLVM CMake export states LLVM version is 15, llvmlite only officially
> >   | supports 20.
> > ```
> 
> This is expected right?

I suppose so, the RTD setup was modified as part of the refactor to cmake. I suppose the expected best resolution would be the following patch:

```
diff --git i/docs/environment.yml w/docs/environment.yml
index 3d190ee6c5..7f8ca55e49 100644
--- i/docs/environment.yml
+++ w/docs/environment.yml
@@ -5,7 +5,7 @@ dependencies:
   - python
   # pip for installing llvmlite itself
   - pip
-  - llvmdev=15
+  - llvmdev=20
   - cmake
   - make
   - docutils==0.16
```

however this will require the existence of an `llvmdev` package on the `numba/label/dev` channel from anaconda.org -- of which there is none yet:


<img width="1270" height="849" alt="Screenshot 2025-08-20 at 12 12 21" src="https://github.com/user-attachments/assets/b616fa2f-8f00-4319-9660-ee27424d152f" />

So the resolution of the RTD build here is blocked until such a package appears (meaning: someone needs to go build it and upload it to anaconda.org).

2025-08-20 17:31 UTC, esc commented
@gmarkall @sklam and @swap357 are currently working on https://github.com/numba/llvmlite/pull/1226 -- once that passes, we can build some `llvmdev` packages suitable for this PR.

2025-08-21 13:30 UTC, esc commented
> @gmarkall @sklam and @swap357 are currently working on #1226 -- once that passes, we can build some `llvmdev` packages suitable for this PR.

The `llvmdev` packages are now available on anaconda.org:

https://anaconda.org/numba/llvmdev/files?channel=llvm20

2025-08-21 13:50 UTC, esc commented
@swap357 do you think it would be possible to re-configure the testing here, to use the `numba/label/llvm20` channel from anaconda.org? Do I need to place the conda packages for the wheel builds in their own channel so they can be differentiated?

2025-08-21 14:58 UTC, swap357 commented
> @swap357 do you think it would be possible to re-configure the testing here, to use the `numba/label/llvm20` channel from anaconda.org? Do I need to place the conda packages for the wheel builds in their own channel so they can be differentiated?

Yes, I can update the configuration for the llvmlite conda builds to use that channel. 
Also yes for the wheel builds, make sense to keep them on one separate channel. Currently, we have them on separate `numba/label/<platform>_wheel`

2025-08-21 15:06 UTC, esc commented
> > @swap357 do you think it would be possible to re-configure the testing here, to use the `numba/label/llvm20` channel from anaconda.org? Do I need to place the conda packages for the wheel builds in their own channel so they can be differentiated?
> 
> Yes, I can update the configuration for the llvmlite conda builds to use that channel. Also yes for the wheel builds, make sense to keep them on one separate channel. Currently, we have them on separate `numba/label/<platform>_wheel`

Please do, and push straight to the PR if you can. I have placed the `llvmdev`s for wheels in the `llvm20-wheel` channel and the other ones in the `llvm20` channel. I think that should be ok, right?

2025-08-22 00:21 UTC, swap357 commented
- updated the GHA workflows and azure pipelines to use the new llvm20 channels. 
- corrected tests to expect missing os linkages 

All CI - azure and GHA are functional now. 
The remaining failures point to formatting errors and RTD will work when llvmdev-20 conda packages are on `numba/label/dev` channel

2025-08-22 08:53 UTC, esc commented
The `llvmdev=20` packages are now available on `numba/label/dev` -- so the RTD build passed too!

2025-08-25 14:39 UTC, esc requested changes
These changes are needed to simplify the build scripts.

2025-08-25 14:39 UTC, esc commented on .github/workflows/llvmlite_conda_builder.yml
> +          activate-environment: cibuild
```suggestion

```

2025-08-25 14:39 UTC, esc commented on .github/workflows/llvmlite_conda_builder.yml
> +          python-version: '3.12'
```suggestion

```

2025-08-25 14:39 UTC, esc commented on .github/workflows/llvmlite_conda_builder.yml
> +              LLVMDEV_CHANNEL="numba/label/llvm20"
```suggestion
              LLVMDEV_CHANNEL="numba/label/dev"
```

2025-08-25 14:39 UTC, esc commented on .github/workflows/llvmlite_conda_builder.yml
> +          python-version: '3.12'
```suggestion

```

2025-08-25 14:39 UTC, esc commented on buildscripts/incremental/setup_conda_environment.cmd
> +call conda install -y -q -c numba/label/llvm20 llvmdev="20.*" libxml2
```suggestion
call conda install -y -q -c numba/label/dev llvmdev=20 libxml2
```

2025-08-25 14:39 UTC, esc commented on buildscripts/incremental/setup_conda_environment.sh
> +$CONDA_INSTALL -c numba/label/llvm20 llvmdev="20.*"
```suggestion
$CONDA_INSTALL -c numba/label/dev llvmdev=20
```

2025-08-25 14:39 UTC, esc commented on buildscripts/manylinux/build_llvmlite.sh
> +    conda install -y -c numba/label/llvm20-wheel llvmdev="20.*" --no-deps
```suggestion
    conda install -y -c numba/label/llvm20-wheel llvmdev=20 --no-deps
```

2025-08-25 14:39 UTC, esc commented on conda-recipes/llvmlite/meta.yaml
> +    - llvmdev 20.*
```suggestion
    - llvmdev 20
```

2025-08-25 16:13 UTC, swap357 commented on .github/workflows/llvmlite_conda_builder.yml
> +          activate-environment: cibuild
I'll revert this back to use - `activate-environment: ""` as this might be required

2025-08-25 16:48 UTC, sklam reviewed
👍  I've reviewed the C++ changes and the main merge to pick up CMake migration.

One minor issue is that this is missing `OrcDebugging`. So just this oneliner https://github.com/sklam/llvmlite/commit/688a910baffeda11909f444c01e00d231d7318d3

2025-08-26 06:54 UTC, swap357 commented
Conda packages and wheels produced by this PR have been tested against `numba/numba` using GitHub Actions (via [numba#10146](https://github.com/numba/numba/pull/10146)). 
CI runs: https://github.com/numba/numba/actions?query=branch%3Apr-10146

Two Windows (win-64) jobs - the conda builder and the wheel builder are currently failing due to known gha issues. Fixes are proposed in [numba#10193](https://github.com/numba/numba/pull/10193) and [numba#10194](https://github.com/numba/numba/pull/10194), with passing validation runs.

2025-08-26 09:26 UTC, esc commented
Based on the tests in https://github.com/numba/numba/pull/10146 -- this is now ready to merge.

2025-08-26 09:27 UTC, merged