Added fneg instruction
numba/llvmlite pull request #685
Opened 2021-01-06 22:03 UTC by Peter-JanGootzen

Whilst following our Compiler Construction course at VU University Amsterdam, we noticed the presence of the `fneg` instruction in LLVM, which was absent in LLVMlite. 
Hence, we decided to make an attempt at adding this instruction.
https://llvm.org/docs/LangRef.html#fneg-instruction

We created a new decorator `_unop` for unary instructions and used that on `fneg`.

2021-01-06 22:44 UTC, 0x5h4un commented
Some code-style checks failed, hence the force push.

2021-01-07 10:17 UTC, esc commented
@Peter-JanGootzen @0x5h4un thank you both for submitting this, I have added it to the queue for review. Awesome to hear you may be using `llvmlite` in your compiler construction course! Can you tell us a little bit more about that (maybe even a hyperlink)?

2021-01-07 13:34 UTC, 0x5h4un commented
@esc Hi there, thanks!

Our course in compiler construction actually requires us to implement parts of a C-like programming language called FenneC, which is designed by the VUSec team using `llvmlite`. This has only been week one out of four, but the first week requires us to implement parts of the front-end involving the lexing, parsing and IR of FenneC. One of the requirements was the implementation of support for arithmetics and definition of floating point numbers, which is why we noticed the absence of `fneg` :). 

If you want, I can give you an update on the entire course and how we used `llvmlite` in about three weeks. In the meantime, [here](https://studiegids.vu.nl/en/Minor/2020-2021/deep-programming/XB_0003) is a link to the course description.

2021-01-07 13:44 UTC, esc commented
@0x5h4un thanks 👍

2021-01-14 15:58 UTC, esc requested changes
I reviewed this today and code and test seem absolutely fine to me. The only thing missing is the documentation. Unfortunately, `llvmlite` comes from a time where it was uncommon to automagically generate API docs from source code, so for now, please manually add a respective entry regarding `fneg` to the following documentation file:

https://github.com/numba/llvmlite/blob/master/docs/source/user-guide/ir/ir-builder.rst#floating-point

Thanks!

2021-01-14 16:00 UTC, esc commented
Pinging @sklam for a second set of eyeballs 👀

2021-01-14 16:03 UTC, sklam reviewed
The code looks good. Just need to add docs.

2021-01-14 16:17 UTC, esc commented
@sklam awesome, thanks! @Peter-JanGootzen @0x5h4un -- just some docs to add and it will be ready for merge.

2021-01-15 11:57 UTC, esc approved these changes
Thank you for fixing this up. I checked the docs locally and they build and render fine. Thank you again for submitting this, will mark as "ready for merge" and it will be merged during the next merge window.

2021-01-25 20:39 UTC, merged

2021-01-25 20:39 UTC, esc commented
@Peter-JanGootzen @0x5h4un congrats on your first contribution to llvmlite!