Fix incorrect `byval` and other attributes on LLVM 14
numba/llvmlite pull request #950
Opened 2023-05-17 20:48 UTC by apmasell

Some attributes now need type information. This preserves it.

2023-05-18 08:50 UTC, esc commented
Two high-level questions from my initial look:

* Can the tests be made to invoke LLVM and check against the produced output, in addition to checking for the "canned" result we have now?

* What happens to the additional parameter attributes that were added in LLVM 14 -- like `byref`? Will you add support for these too?

2023-05-18 13:33 UTC, apmasell commented
For the first, I don't know how to do that given the way I can get the plumbing to work with pickle. If you have a design, I'm happy to hear it.

For the second, until we have a true way to control LLVM backend version, we should only do that if we raise the minimum LLVM version. Are we prepared to do that in a patch release?

2023-05-19 03:42 UTC, thomasfire commented
> For the first, I don't know how to do that given the way I can get the plumbing to work with pickle. If you have a design, I'm happy to hear it.

Is it possible to integrate these pieces of IR from tests to some function and see if LLVM compiles it?

2023-05-19 12:44 UTC, apmasell commented
That's what the current test does.

2023-05-25 10:35 UTC, esc commented
OK, so just to double check, the way this works now:

a) We have code to add the types to the Parameter Attributes
b) The "canned" tests have been updated, but they only test for the `sret` parameter attribute
c) We have a generated test, where we test `byval` -- such that we generate some IR and then ensure that the given version of LLVM can indeed parse this IR

The question I have, and I have no idea if this even needs to be asked: so it seems that we only check for `sret` and `byval`, but these are not the only parameter attributes? Do we need to -- or should we -- test the other attributes too?

The second question that I have is if we can ask anyone from the `artiq` project to check this PR with their code? This is where these issues were originally detected, and perhaps this is a good test case for this PR: https://github.com/m-labs/artiq/issues/2050 @thomasfire would you be able to facilitate this?

2023-05-26 21:41 UTC, apmasell commented
Added.

2023-05-29 03:53 UTC, thomasfire commented
I've tested our code against this branch, and would confirm that this fixes the issue

2023-05-29 10:40 UTC, esc commented
> I've tested our code against this branch, and would confirm that this fixes the issue

Awesome, thank you for your feedback! 

@thomasfire would you like to be added to our RC-Testers group on our discourse: 

https://numba.discourse.group/

it's a group of folks who are interested in new Numba/llvmlite release candidates, perhaps this could be of interest to you? It would perhaps help with future llvmlite testing?

2023-05-30 02:08 UTC, thomasfire commented
> would you like to be added to our RC-Testers group on our discourse:

Yes, you can add me, username is same as github's

2023-05-31 12:33 UTC, esc requested changes
I have a suggestion to make about using slightly more Pythonic syntax.

2023-05-31 12:33 UTC, esc commented on llvmlite/ir/values.py
> +        return list(map(lambda a: self._expand(a, typ), iter(sorted(self))))
Could this be converted to?

```suggestion
        return [self.expand(i, typ) for i in sorted(self)]
```

2023-06-01 11:16 UTC, esc commented
> > would you like to be added to our RC-Testers group on our discourse:
> 
> Yes, you can add me, username is same as github's

You should have received an invite now.

2023-06-01 12:15 UTC, esc commented
Since this also supports LLVM 11 -- I was wanting to build this PR and test against that. However, I am having trouble getting a development environment setup. Mostly I am troubled with conda environment conflicts.

2023-06-02 01:21 UTC, apmasell commented
I've added a commit that should make it work properly on LLVM 11. Some of the attributes being tested weren't supported on LLVM 11.

2023-06-02 11:28 UTC, esc commented
> I've added a commit that should make it work properly on LLVM 11. Some of the attributes being tested weren't supported on LLVM 11.

Thank you, I can confirm that with the commit efb856a the llvmlite test suite passes with LLVM 11.

2023-06-02 13:09 UTC, apmasell commented
That's exciting and I desperately hope not related to these changes.

2023-06-02 13:20 UTC, esc commented
> That's exciting and I desperately hope not related to these changes.

No, it wasn't, it was a side effect of not having pyyaml installed.

2023-06-02 14:36 UTC, esc commented
I am now hitting:

```
.Assertion failed: (isInt<33>(Addend) && "Invalid page reloc value."), function encodeAddend, file /Users/ci/miniconda3-arm64/conda-bld/llvmdev_1643905487494/work/lib/ExecutionEngine/RuntimeDyld/Targets/RuntimeDyldMachOAArch64.h, line 210.
Fatal Python error: Aborted

Current thread 0x0000000104d34580 (most recent call first):
  File "/Users/vhaenel/git/llvmlite/llvmlite/binding/ffi.py", line 152 in __call__
  File "/Users/vhaenel/git/llvmlite/llvmlite/binding/executionengine.py", line 92 in finalize_object
  File "/Users/vhaenel/git/numba/numba/core/codegen.py", line 1060 in wrapper
  File "/Users/vhaenel/git/numba/numba/core/codegen.py", line 999 in _finalize_specific
  File "/Users/vhaenel/git/numba/numba/core/codegen.py", line 797 in _finalize_final_module
```

Which I believe is known issue on Mac ARM64?

2023-06-02 15:26 UTC, esc commented
> I am now hitting:
> 
> ```
> .Assertion failed: (isInt<33>(Addend) && "Invalid page reloc value."), function encodeAddend, file /Users/ci/miniconda3-arm64/conda-bld/llvmdev_1643905487494/work/lib/ExecutionEngine/RuntimeDyld/Targets/RuntimeDyldMachOAArch64.h, line 210.
> Fatal Python error: Aborted
> 
> Current thread 0x0000000104d34580 (most recent call first):
>   File "/Users/vhaenel/git/llvmlite/llvmlite/binding/ffi.py", line 152 in __call__
>   File "/Users/vhaenel/git/llvmlite/llvmlite/binding/executionengine.py", line 92 in finalize_object
>   File "/Users/vhaenel/git/numba/numba/core/codegen.py", line 1060 in wrapper
>   File "/Users/vhaenel/git/numba/numba/core/codegen.py", line 999 in _finalize_specific
>   File "/Users/vhaenel/git/numba/numba/core/codegen.py", line 797 in _finalize_final_module
> ```
> 
> Which I believe is known issue on Mac ARM64?

It is this one here: https://github.com/numba/numba/issues/8567

OK, I ran it again and it seems like the issue is transient, so I would say this did indeed pass a spot check, with LLVM 11.

2023-06-05 08:45 UTC, esc requested changes
Question: can we compile?

2023-06-05 08:45 UTC, esc commented on llvmlite/tests/test_ir.py
> +            llvm.parse_assembly(gen_code(attr_name))
Would it be possible to try to compile this too? Or is the test-code not self-sufficient?

2023-06-05 14:08 UTC, esc commented on llvmlite/tests/test_ir.py
> +            llvm.parse_assembly(gen_code(attr_name))
ok, that makes sense, thank you.

2023-06-05 16:42 UTC, esc commented
This is now going in, thank you for the patch!

2023-06-05 16:42 UTC, merged